name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: testenv

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      env:
        GPR_USER: ${{ secrets.GPR_USER }}
        GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
#    - name: Setup env variables
#      env:
#        GPR_USER: ${{ secrets.GPR_USER }}
#        GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew printCreds build
